"""Phase 10 active-learning re-ranker adjustment script.

Reads accumulated user-feedback rows from the PostgreSQL-compatible audit
database and adjusts per-standard relevance boosts/penalties stored in
data/local/reranker_proposal.json.

Algorithm (simple, reversible, transparent):
  • 'reject' decision  → subtract DELTA from that standard's boost (floor −1.0)
  • 'correct' decision → add    DELTA to the suggested standard's boost (ceil +1.0)
  • Boosts decay by DECAY_PER_DAY × days_since_signal toward zero each run
    (prevents stale early feedback from dominating over time).

This command produces an UNREVIEWED research proposal. The serving engine
never loads these global boosts: a query-independent popularity adjustment can
harm relevance. Evaluate query-specific training with held-out officer labels
before promoting any future ranking change.

DATABASE_URL must refer to the local audit database. Use --synthetic-demo
explicitly for simulated signals; synthetic proposals are isolated.
"""
import argparse
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
log = logging.getLogger('retrain_reranker')

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_BOOSTS_PATH = ROOT / 'data/local/reranker_proposal.json'
DEFAULT_LOG_PATH = ROOT / 'data/local/reranker_proposal_log.jsonl'

DELTA = 0.1           # Boost step per feedback signal
DECAY_PER_DAY = 0.007 # Decay rate toward zero per day (≈5% per week)
FLOOR = -1.0          # Minimum boost
CEILING = 1.0         # Maximum boost


def load_boosts(path: Path) -> dict:
    """Load existing boosts file or start fresh."""
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
            log.info('Loaded %d existing boost entries from %s', len(data.get('boosts', {})), path)
            return data
        except Exception as exc:
            log.warning('Could not load boosts file (%s); starting fresh.', exc)
    return {
        '_warning': (
            'Auto-generated by scripts/retrain_reranker.py.  '
            'Research proposal only; never applied by the serving engine.  '
            'Delete this file to reset all boosts to zero.'
        ),
        'boosts': {},          # is_number → float
        'signal_counts': {},   # is_number → {'reject': int, 'correct': int}
        'last_updated': None,
        'processed_feedback_ids': [],
    }


def save_boosts(data: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
    log.info('Boosts saved → %s', path)


def append_log(entry: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as f:
        f.write(json.dumps(entry, ensure_ascii=False) + '\n')


def clamp(value: float) -> float:
    return max(FLOOR, min(CEILING, value))


def decay_boosts(data: dict, now: datetime) -> int:
    """Decay all existing boosts toward zero based on time since last update.
    Returns number of boosts decayed."""
    last_str = data.get('last_updated')
    if not last_str:
        return 0
    try:
        last = datetime.fromisoformat(last_str)
    except ValueError:
        return 0
    days_elapsed = (now - last).total_seconds() / 86400.0
    if days_elapsed <= 0:
        return 0
    decay = DECAY_PER_DAY * days_elapsed
    boosts = data['boosts']
    decayed = 0
    for key in list(boosts.keys()):
        v = boosts[key]
        if v > 0:
            boosts[key] = max(0.0, v - decay)
            decayed += 1
        elif v < 0:
            boosts[key] = min(0.0, v + decay)
            decayed += 1
        # Remove near-zero boosts to keep the file small.
        if abs(boosts[key]) < 0.001:
            del boosts[key]
    return decayed


def fetch_feedback(processed_ids: list) -> list[dict]:
    """Fetch unprocessed feedback rows from the audit database.

    Fails closed if the database is unavailable.
    Returns a list of dicts with keys: id, decision, record_id, comment,
    created_at.
    """
    try:
        from services.recommendation.audit import PostgresAudit
        audit = PostgresAudit()
        try:
            placeholders = ', '.join(['%s'] * len(processed_ids)) if processed_ids else 'NULL'
            query = (
                f"SELECT id::text, decision, record_id, comment, created_at::text "
                f"FROM kb.user_feedback "
                f"{'WHERE id::text NOT IN (' + placeholders + ')' if processed_ids else ''} "
                f"ORDER BY created_at ASC"
            )
            rows = audit.connection.execute(query, processed_ids if processed_ids else None).fetchall()
            return [{'id': r[0], 'decision': r[1], 'record_id': r[2],
                     'comment': r[3], 'created_at': r[4]} for r in rows]
        finally:
            audit.close()
    except Exception as exc:
        raise RuntimeError('Feedback database unavailable; no simulated feedback was substituted. Use --synthetic-demo explicitly for a fixture proposal.') from exc


def _demo_feedback(processed_ids: list) -> list[dict]:
    """Return synthetic feedback rows for offline demo when DB is unavailable.
    These are clearly labeled and do not represent real user signals."""
    existing = set(processed_ids)
    demo = [
        {'id': 'demo-fb-001', 'decision': 'reject',  'record_id': 'bis-17',
         'comment': 'Wrong standard returned for ceramic tile query',
         'created_at': '2026-09-22T10:00:00+00:00'},
        {'id': 'demo-fb-002', 'decision': 'correct', 'record_id': 'bis-12',
         'comment': 'IS 15622:2017 is the right standard for pressed ceramic tiles',
         'created_at': '2026-09-22T10:01:00+00:00'},
        {'id': 'demo-fb-003', 'decision': 'reject',  'record_id': 'bis-13',
         'comment': 'Eye protector returned for breathing apparatus query',
         'created_at': '2026-09-22T10:02:00+00:00'},
    ]
    return [d for d in demo if d['id'] not in existing]


def load_record_map() -> dict[str, str]:
    """Map record_id → is_number from the seed corpus."""
    from services.ingestion.records import read_records
    return {r['record_id']: r['is_number'] for r in read_records()}


def main():
    global DECAY_PER_DAY
    parser = argparse.ArgumentParser(description='StandX Phase 10 active-learning re-ranker')
    parser.add_argument('--delta', type=float, default=DELTA,
                        help=f'Boost step per feedback signal (default {DELTA})')
    parser.add_argument('--decay', type=float, default=DECAY_PER_DAY,
                        help=f'Boost decay per day toward zero (default {DECAY_PER_DAY})')
    parser.add_argument('--boosts-path', default=str(DEFAULT_BOOSTS_PATH),
                        help='Path to reranker_boosts.json')
    parser.add_argument('--log-path', default=str(DEFAULT_LOG_PATH),
                        help='Path to reranker_boosts_log.jsonl')
    parser.add_argument('--dry-run', action='store_true',
                        help='Compute changes but do not write files')
    parser.add_argument('--synthetic-demo', action='store_true', help='Explicit fixture proposal; never used by serving')
    args = parser.parse_args()
    import math
    if not all(math.isfinite(v) and 0 <= v <= 1 for v in (args.delta,args.decay)):
        parser.error('delta and decay must be finite values in [0,1]')

    boosts_path = Path(os.environ.get('RERANKER_BOOSTS_PATH', args.boosts_path))
    log_path = Path(args.log_path)
    if args.synthetic_demo:
        boosts_path=ROOT / 'data/local/synthetic_reranker_proposal.json'
        log_path=ROOT / 'data/local/synthetic_reranker_proposal_log.jsonl'
    delta = args.delta
    DECAY_PER_DAY = args.decay



    log.info('StandX retrain_reranker starting (delta=%.3f, decay_per_day=%.4f)', delta, DECAY_PER_DAY)

    data = load_boosts(boosts_path)
    now = datetime.now(timezone.utc)

    # Decay first so newly processed signals are not double-decayed.
    n_decayed = decay_boosts(data, now)
    log.info('Decayed %d boost entries toward zero', n_decayed)

    record_map = load_record_map()
    processed_ids = data.get('processed_feedback_ids', [])
    rows = _demo_feedback(processed_ids) if args.synthetic_demo else fetch_feedback(processed_ids)
    data['review_status']='unreviewed_proposal'
    data['source']='synthetic_seed' if args.synthetic_demo else 'officer_feedback'
    data['_warning']='Research proposal only. Never loaded by the serving engine.'
    log.info('Fetched %d new feedback rows', len(rows))

    changes = []
    for row in rows:
        rid = row['record_id']
        decision = row['decision']
        is_number = record_map.get(rid)
        if not is_number:
            log.warning('record_id %s not found in KB; skipping feedback %s', rid, row['id'])
            continue

        boosts = data.setdefault('boosts', {})
        counts = data.setdefault('signal_counts', {})
        old = boosts.get(is_number, 0.0)

        if decision == 'reject':
            new_val = clamp(old - delta)
            direction = 'penalty'
        elif decision == 'correct':
            new_val = clamp(old + delta)
            direction = 'boost'
        else:
            # 'confirm' — no adjustment needed (positive signal keeps current boost)
            log.debug('Skipping confirm feedback %s', row['id'])
            processed_ids.append(row['id'])
            continue

        boosts[is_number] = new_val
        sc = counts.setdefault(is_number, {'reject': 0, 'correct': 0})
        sc[decision] = sc.get(decision, 0) + 1

        change = {
            'feedback_id': row['id'],
            'decision': decision,
            'record_id': rid,
            'is_number': is_number,
            'direction': direction,
            'old_boost': round(old, 4),
            'new_boost': round(new_val, 4),
            'timestamp': now.isoformat(),
        }
        changes.append(change)
        processed_ids.append(row['id'])
        log.info('%s: %s → boost %+.4f → %+.4f', is_number, direction, old, new_val)

    data['last_updated'] = now.isoformat()
    data['processed_feedback_ids'] = processed_ids

    # Summary
    print()
    print('=' * 60)
    print('StandX active-learning boost update')
    print('=' * 60)
    print(f'  New feedback signals processed : {len(changes)}')
    print(f'  Total boost entries            : {len(data["boosts"])}')
    print(f'  Boosts decayed (time-weighted) : {n_decayed}')
    print()
    if changes:
        print('  Changes:')
        for c in changes:
            print(f'    [{c["is_number"]}]  {c["direction"]:8s}  {c["old_boost"]:+.4f} → {c["new_boost"]:+.4f}  ({c["decision"]})')
    else:
        print('  No actionable feedback signals found.')
    print()

    if args.dry_run:
        print('DRY RUN — no files written.')
        return

    save_boosts(data, boosts_path)
    log_entry = {
        'run_timestamp': now.isoformat(),
        'delta': delta,
        'decay_per_day': DECAY_PER_DAY,
        'new_signals': len(changes),
        'boosts_decayed': n_decayed,
        'changes': changes,
        'total_boost_entries': len(data['boosts']),
    }
    append_log(log_entry, log_path)
    log.info('Run log appended → %s', log_path)


if __name__ == '__main__':
    main()
